# Generated by Django 5.2.1 on 2025-07-28 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_cancellation_reason_booking_cancelled_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingCalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_event_id', models.CharField(help_text="ID of the event in the user's Google Calendar", max_length=255, verbose_name='Google Calendar Event ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='bookings.booking', verbose_name='Related Booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Owning the Calendar Event')),
            ],
            options={
                'verbose_name': 'Booking Calendar Event',
                'verbose_name_plural': 'Booking Calendar Events',
                'unique_together': {('booking', 'user')},
            },
        ),
    ]
