# Generated by Django 5.2.1 on 2025-06-03 08:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentdetails',
            options={'verbose_name': 'Student Detail', 'verbose_name_plural': 'Student Details'},
        ),
        migrations.RemoveField(
            model_name='studentdetails',
            name='interests',
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='additional_notes',
            field=models.TextField(blank=True, help_text='Any additional notes or preferences', null=True),
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='fields_of_interest',
            field=models.JSONField(default=list, help_text='List of fields the student is interested in (e.g., Computer Science, Business)'),
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='interested_universities',
            field=models.JSONField(default=list, help_text='List of universities the student is interested in'),
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='mentorship_preferences',
            field=models.JSONField(default=list, help_text='List of preferred mentorship types'),
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='preferred_countries',
            field=models.JSONField(default=list, help_text='List of preferred study countries'),
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='education_level',
            field=models.CharField(choices=[('high_school', 'High School'), ('bachelors', "Bachelor's Degree"), ('masters', "Master's Degree"), ('phd', 'PhD'), ('other', 'Other')], default='high_school', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
