# Generated by Django 5.2.1 on 2025-06-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_studentdetails_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='student_profile_pics/'),
        ),
    ]
