# Generated by Django 5.2.1 on 2025-06-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_studentdetails_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='education_level',
            field=models.CharField(default='high_school', max_length=50),
        ),
    ]
