# Generated by Django 5.2.1 on 2025-09-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('connection_request_received', 'Connection Request Received'), ('connection_request_accepted', 'Connection Request Accepted'), ('connection_request_cancelled', 'Connection Request Cancelled'), ('session_cancelled', 'Session Cancelled'), ('mentor_approved', 'Mentor Approved'), ('mentor_rejected', 'Mentor Rejected'), ('booking_cancelled', 'Booking Cancelled'), ('message_received', 'Message Received')], max_length=50),
        ),
    ]
