# Generated by Django 6.0.7 on 2026-07-28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="LearnAISummary",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("youtube_url", models.URLField(max_length=500)),
                ("video_id", models.CharField(db_index=True, max_length=32)),
                ("video_title", models.CharField(max_length=500)),
                ("transcript", models.TextField()),
                ("summary", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("student", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="learn_ai_summaries", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ("-created_at",)},
        ),
        migrations.AddIndex(
            model_name="learnaisummary",
            index=models.Index(fields=["student", "-created_at"], name="learn_ai_le_student_0806c9_idx"),
        ),
    ]
