# Generated by Django 5.2.1 on 2025-05-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0003_remove_mentordetails_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentordetails',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='mentor_profile_pics/'),
        ),
    ]
