# Generated by Django 5.2.1 on 2025-06-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0004_mentordetails_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentordetails',
            name='last_status_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mentordetails',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentordetails',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_revision', 'Needs Revision')], default='pending', max_length=15),
        ),
    ]
