# Generated by Django 5.2.1 on 2025-06-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0005_mentordetails_last_status_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentordetails',
            name='countries',
            field=models.JSONField(default=list, help_text="List of country codes (e.g., ['US', 'UK'])"),
        ),
        migrations.AddField(
            model_name='mentordetails',
            name='courses',
            field=models.JSONField(default=list, help_text="List of courses (e.g., ['Computer Science', 'Data Science'])"),
        ),
    ]
