# Generated by Django 5.2.1 on 2025-07-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0009_alter_slot_mentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('cancelled', 'Cancelled by Mentor'), ('completed', 'Completed'), ('unavailable', 'Unavailable')], default='available', max_length=20),
        ),
    ]
