# Generated by Django 5.2.1 on 2025-07-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0010_alter_slot_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentordetails',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mentordetails',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_revision', 'Needs Revision'), ('INCOMPLETE', 'Incomplete Setup')], default='pending', max_length=15),
        ),
    ]
